services:
  db:
    image: postgres:17.2-alpine
    environment:
      - TZ=UTC
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
      - POSTGRES_DB=resizer
    ports:
      - "6432:5432"
    healthcheck:
      test: "pg_isready -U user -d resizer"
      interval: 5s
      timeout: 5s
      retries: 100

  minio:
    image: minio/minio:RELEASE.2024-02-09T21-25-16Z
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_DOMAIN: minioS3
    entrypoint: sh

    command: |
      -c '
      mkdir -p /data/files &&
      minio server --console-address :9001 /data'
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      retries: 5
      timeout: 5s

